@baseUrl = http://localhost:5000/

POST {{{baseUrl}}}
Content-Type: application/json

{
    "name":"Hoài Sang",
    "email": "hoai.sang050@gmail.com",
    "password": "hoai.sang050@gmail.com",
    "phone_number": "0944552050"
    
}